### ISSUE TITLE
Blank screen after activation on empty site

### ISSUE THREAD

**Issue by carletto0282** [inpsyde/wpml2mlp#12]
Hi,

I've got an empty site.
Just installed Multilingual Press (free version) and WPML to MLP.

When I "network activate" wpml to mlp I've got this error

Fatal error: Call to a member function get_name() on string in /mysite/wp-content/plugins/multilingual-press/inc/db/Mlp_Content_Relations.php on line 47

**Comment by bueltge** [comment]
@carletto0282 Do you use the WPML2MLP version from the w.org repository or the git version? Background is, that we have much more improvements in the git version.

**Comment by carletto0282** [comment]
Hi bueltge,

I'm using the one from the wp repository.
I thought they were the same.

No problem I'm gonna check the git version.
Thanks

**Comment by carletto0282** [comment]
Hi @bueltge ,

same error occured using the git version of the plugin.

**Comment by sanelaj** [comment]
Please check

**Comment by s7nkuridza** [comment]
Error is now prevented, changes are on master branch.

**Comment by sanelaj** [comment]
@carletto0282 Please test and close the issue
