### ISSUE TITLE
Missing file /inc/Wpml2mlp_Categorie_Creator.php in wordpress package

### ISSUE THREAD

**Issue by ajaegers** [inpsyde/wpml2mlp#13]
Hello,

Missing file /inc/Wpml2mlp_Categorie_Creator.php in wordpress package at https://downloads.wordpress.org/plugin/wpml-to-multilingualpress.zip 

Link from  https://wordpress.org/plugins/wpml-to-multilingualpress/

Thanks

**Comment by bueltge** [comment]
Thanks for the hint, SVN problem ;( 
Now the file was include the zip from w.org.

**Comment by ajaegers** [comment]
You're welcome.
