### ISSUE TITLE
Import: Can't upload zip which was created by the export

### ISSUE THREAD

**Issue by luminuu** [inpsyde/wpml2mlp#17]
When uploading an WPML2MLP generated ZIP file, the following error occurs:

![image](https://cloud.githubusercontent.com/assets/7585600/11060137/a5772970-879e-11e5-9958-0ec9f723cdbc.png)

This is the output of the plugin Debug Bar. The WPML2MLP plugin does not give any error messages to the user.

**Comment by derpixler** [comment]
we have replaced the zip with gzip and added a new xml export format.
