### ISSUE TITLE
Export: Memory leck on bigdata

### ISSUE THREAD

**Issue by derpixler** [inpsyde/wpml2mlp#33]
`Fatal error: Maximum execution time of 30 seconds exceeded ... `

If we have a lot of content at the source blog the execution needs more time we have.

refactor the export see https://stackoverflow.com/questions/3212982/need-to-write-xml-using-php-how and http://php.net/XMLWriter

**Comment by dnaber-de** [comment]
The XMLWriter won't reduce the execution time but probably the memory usage. It further might be possible that the writing process can be split to multiple processes and thus to more than one http request.

Anyway, we have to cancel the time limit with `set_time_limit( 0 )`.

**Comment by derpixler** [comment]
The leck is also open.
