### ISSUE TITLE
[Exporter] Filter for Termtypes

### ISSUE THREAD

**Issue by bueltge** [inpsyde/wpml2mlp#58]
Please provide also a filter hook for the term types, so that users can change the default, like custom terms. You should enhance this like the post filter [`wpml2mlp_supported_posttypes`](https://github.com/inpsyde/wpml2mlp/blob/2.0.0/inc/Wpml2mlp_Helper.php#L35).

https://github.com/inpsyde/wpml2mlp/blob/2.0.0/inc/Wpml2mlp_Helper.php#L25

**Comment by derpixler** [comment]
Implement a filter for terms `wpml2mlp_export_supported_terms` more see here https://github.com/inpsyde/wpml2mlp/blob/2.0.0/inc/Wpml2mlp_Helper.php#L19

**Example (modern)**
```php
add_filter( 'wpml2mlp_export_supported_terms', function( $terms ){
	$terms['countries'] = 'countries';
	return $terms;
});
```

**Example (classic)**
```php
add_filter( 'wpml2mlp_export_supported_terms', 'add_custom_term' );

function add_woo( $terms ){
	$terms['countries'] = 'countries';
	return $terms;
}
```
