### ISSUE TITLE
Build on w.org does not contain assets

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/wpml2mlp#63]
Reported by @derpixler 

The assets directory is missing in the w.org repository: https://plugins.trac.wordpress.org/browser/wpml-to-multilingualpress/trunk

**Comment by bueltge** [comment]
Released is the tag 2.0.0, missed also the assets directory. Now added in trunk and tag 2.0.0

**Comment by derpixler** [comment]
Oky here is another one! 

For the import we use a autoload installed via composer. 
https://github.com/inpsyde/wpml2mlp/blob/master/wpml2mlp.php#L40

This file is also missing in plugins folder… '/vendor/autoload.php'

**Comment by bueltge** [comment]
The vendor directory include all composer files are now also on w.org.
