### ISSUE TITLE
Notice: Undefined variable: wp_is_multisite_check

### ISSUE THREAD

**Issue by bueltge** [inpsyde/wpml2mlp#7]
`Notice: Undefined variable: wp_is_multisite_check in /var/www/wp-plugins/wpml2mlp/inc/Wpml2mlp_Prerequisites.php on line 24`

at the load after login on Dashboard. 
`WP_DEBUG` is `TRUE` and [xdebug](http://xdebug.org/) is active

**Comment by kraftner** [comment]
Same issue here.

Running on a fresh [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) stack in case this helps when reproducing the issue.

**Comment by sanelaj** [comment]
@bueltge What is the timeline for this fix?

**Comment by bueltge** [comment]
The customer project are priority 1. Buy a small fix for this issue would be fine.

**Comment by sanelaj** [comment]
Please check this issue, a fix was commited yesterday

**Comment by bueltge** [comment]
Sollte so passen.
