### ISSUE TITLE
Persistent activation errors

### ISSUE THREAD

**Issue by Drivingralle** [inpsyde/wpml2mlp#8]
I tried to activate the plugin on a single site install:
1. with no other plugins active. -> Error: WPML is needed.
2. with WPML active -> Error: Multisite needed.

In both cases I couldn't return to the plugin list, to deactivate the plugin. The wp_die() always blocked access. Needed to rename the plugins folder. -> Possible but annoying.

Auto deactivate the plugin on fail with an error on top of the list would be nice.

**Comment by sanelaj** [comment]
Please deactivate WPML2MLP in the described case and show the error message "Please ensure, that you have set up a multisite environment and activated WPML."
