### ISSUE TITLE
Failed to move categories

### ISSUE THREAD

**Issue by Drivingralle** [inpsyde/wpml2mlp#9]
I converted a lower german website with the plugin and the categories didn't make it into the new sites. There is just the uncategorized category.

Here the original category list, it's still complete in the base site:
![bildschirmfoto 2015-07-23 um 12 27 39](https://cloud.githubusercontent.com/assets/1727269/8848269/3f76cfea-3136-11e5-95fb-eca3e39bbeb9.jpg)

**Comment by bueltge** [comment]
@Drivingralle Thanks again for your hint. Can you test the enhancement and give a feedback?

**Comment by Drivingralle** [comment]
I will. May take some days to find time for it.
